name: Deploy Middleman site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Set up Git user
        run: |
          git config --global user.name "trug-bot"
          git config --global user.email "trug-bot@trug.it"

      - name: Fix remote URL with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/3cityRUG/TRUG.git

      - name: Update RubyGems
        run: gem update --system

      - name: Install dependencies
        run: bundle install

      - name: Run rake publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec rake publish
